name: Post Artifacts
run-name: Posting Artifacts

jobs:
  post-test-results:
    runs-on: ubuntu-latest
    steps:
      - name: post allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-regression-results
          path: allure-results

      - name: post application logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-logs
          path: logs
