name: Regression Suite
run-name: Regression Tests

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  BASE_UI_URL: ${{ secrets.BASE_UI_URL }}
  BASE_API_URL: ${{ secrets.BASE_API_URL }}
  IMPLICIT_DRIVER_WAIT: ${{ secrets.IMPLICIT_DRIVER_WAIT }}
  BROWSER: ${{ secrets.BROWSER }}

jobs:
  call-smoke-run:
    uses: ./.github/workflows/smoke.yml

  regression-run:
    needs: call-smoke-run
    runs-on: ubuntu-latest
    steps:
      - name: setup project
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: install dependecies
        run: pip install -r requirements.txt

      - name: run tests
        run: pytest -n auto -m regression --alluredir=allure-results

      - name: post allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-regression-results
          path: allure-results

      - name: post application logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: regression-logs
          path: logs