name: Smoke Suite
run-name: Smoke Tests

on:
  workflow_call:
    secrets:
      BASE_UI_URL:
        required: true
      BASE_API_URL:
        required: true
      BASE_JIRA_API_URL:
        required: true
      JIRA_USER:
        required: true
      JIRA_PASSWORD:
        required: true
  workflow_dispatch:
  pull_request:
    branches: [ main ]

env:
  BASE_UI_URL: ${{ secrets.BASE_UI_URL }}
  BASE_API_URL: ${{ secrets.BASE_API_URL }}
  BASE_JIRA_API_URL: ${{ secrets.BASE_JIRA_API_URL }}
  JIRA_USER: ${{ secrets.JIRA_USER }}
  JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}

jobs:
  initial-run:
    continue-on-error: true
    strategy:
      matrix:
        application: [jira, petstore]
    runs-on: ubuntu-latest
    steps:
      - name: setup project
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: run API tests
        continue-on-error: true
        run: pytest src/test/api/${{ matrix.application }}  -n auto -m smoke --alluredir=allure-results

      - name: post allure results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.application }}-allure-smoke-results
          path: allure-results

      - name: post application logs
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.application }}-smoke-logs
          path: logs
