name: Python tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: pytest -v

      - name: Run tests and generate report
        run: |
          pytest --maxfail=1 --disable-warnings -v --tb=short --html=report.html

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: report.html
