name: UI Suite
run-name: UI Tests

on:
  pull_request:
  workflow_dispatch:
    inputs:
      TEST_TYPE:
        description: Type of tests that must be run. "api" or "ui"
        required: true
        type: string
        default: 'ui'

env:
  TEST_TYPE: ${{ github.event.inputs.TEST_TYPE || vars.TEST_TYPE}}
  BASE_UI_URL: ${{ secrets.BASE_UI_URL }}
  BASE_API_URL: ${{ secrets.BASE_API_URL }}
  IMPLICIT_DRIVER_WAIT: ${{ secrets.IMPLICIT_DRIVER_WAIT }}
  BROWSER: ${{ secrets.BROWSER }}
  BASE_JIRA_API_URL: ${{ secrets.BASE_JIRA_API_URL }}
  JIRA_USER: ${{ secrets.JIRA_USER }}
  JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}

jobs:
  initial-run:
    runs-on: ubuntu-latest
    steps:
      - name: setup project
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: run tests
        run: pytest -n auto -m ${{ env.TEST_TYPE }} --alluredir=allure-results

      - name: post allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-ui-results
          path: allure-results

      - name: post application logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-logs
          path: logs
